# Generated by Django 4.1.7 on 2024-08-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_name', models.CharField(max_length=100)),
                ('vintage', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('grape_variety', models.CharField(max_length=100)),
                ('wine_type', models.CharField(max_length=100)),
            ],
        ),
    ]
