# Generated by Django 4.1.7 on 2024-08-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_television'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tyres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=50)),
                ('load_speed', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('load_range', models.CharField(max_length=50)),
                ('performance_type', models.CharField(max_length=50)),
                ('date_of_extraction', models.DateField()),
                ('source', models.CharField(max_length=255)),
            ],
        ),
    ]
