# Generated by Django 4.1.7 on 2024-08-20 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_tyres'),
    ]

    operations = [
        migrations.AddField(
            model_name='television',
            name='date_of_extraction',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
        migrations.AddField(
            model_name='television',
            name='source',
            field=models.CharField(default='https://www.dubaistore.com/ae-en/search?all-categories-home=&q=television', max_length=255),
        ),
    ]
