# Generated by Django 4.1.7 on 2024-08-20 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0004_television_date_of_extraction_television_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='television',
            name='date_of_extraction',
            field=models.DateField(default=datetime.date(2024, 8, 10)),
        ),
    ]
