# Generated by Django 4.1.7 on 2024-08-20 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_alter_television_date_of_extraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='television',
            name='date_of_extraction',
        ),
        migrations.RemoveField(
            model_name='television',
            name='source',
        ),
    ]
