# Generated by Django 4.1.7 on 2024-08-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0006_remove_television_date_of_extraction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lubricants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('capacity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('measure', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('date_of_extraction', models.DateField()),
            ],
        ),
    ]
