# Generated by Django 4.1.7 on 2024-08-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0007_lubricants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lubricants',
            name='capacity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lubricants',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
