# Generated by Django 4.1.7 on 2024-08-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0008_alter_lubricants_capacity_alter_lubricants_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=100)),
                ('measure', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=100)),
                ('product_url', models.URLField()),
                ('date_of_extraction', models.DateField()),
            ],
        ),
    ]
