# Generated by Django 4.1.7 on 2024-08-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0010_carpets_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpets',
            name='product_url',
            field=models.CharField(max_length=100),
        ),
    ]
