# Generated by Django 4.1.7 on 2024-08-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0014_rename_engine_type_car_engine_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(),
        ),
    ]
