# Generated by Django 4.1.7 on 2024-08-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0015_alter_car_mileage_alter_car_type_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=50),
        ),
    ]
