# Generated by Django 4.1.7 on 2024-08-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0016_alter_car_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Glass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('min_order', models.CharField(max_length=100)),
                ('measure', models.CharField(max_length=100)),
                ('date_of_extraction', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
